- name: deployment of kubernetes application
  hosts: minikube
  become: true
  user: root
  tasks:
  - name: run helm command
    command: helm ls
  - name: install kubernetes deployment
    command: helm install helloworld ./helloworld 
    args:
      chdir: /home/jenkinsusr/package
  