- name: deployment of kubernetes application
  hosts: minikube
  become: true
  user: root
  tasks:
  - name: run helm command
    command: helm install helloworld ./helloworld
    args:
      chdir: /home/ansadmin/package
  