- name: deployment of kubernetes application
  hosts: minikube
  become: true
  user: root
  tasks:
  - name: run helm command
    command: helm ls
  - name: install/update kubernetes deployment
    block:
       - name: install helm
         command: helm install helloworld ./helloworld 
         args:
           chdir: /home/jenkinsusr/package
    rescue:
       - name: upgrade the deployment
         command: helm upgrade helloworld ./helloworld 
         args:
           chdir: /home/jenkinsusr/package
  